# Generated by Django 4.0.1 on 2022-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_trainingmodel_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodel',
            name='sim_seen_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='sim_unseen_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='training_data_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='wand_score',
            field=models.IntegerField(null=True),
        ),
    ]
