# Generated by Django 4.0.1 on 2022-04-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_remove_simulationmodel_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodel',
            name='loss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodel',
            name='metrics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodel',
            name='normalization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodel',
            name='optimizer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
