# Generated by Django 4.0.1 on 2022-03-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('hostname', models.CharField(blank=True, max_length=40, null=True)),
                ('command', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
