# Generated by Django 4.0.2 on 2022-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runqueue',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runqueue',
            name='hostname',
            field=models.CharField(choices=[('sal5', 'sal5'), ('sal4', 'sal4')], default=None, max_length=40),
            preserve_default=False,
        ),
    ]
