"Models for Modeladmin"
from django.db import models

class TrainingModel(models.Model):
    description = models.CharField(max_length=200,  null=True )
    date = models.DateTimeField('date created',  null=True)
    hostname = models.CharField(max_length=40,  null=True)
    history_path = models.CharField(max_length=200,  null=True)
    model_path = models.CharField(max_length=200,  null=True)
    figures_dir = models.CharField(max_length=200,  null=True)
    dict_text_output_path = models.CharField(max_length=200,  null=True)
    checkpoint_path = models.CharField(max_length=200,  null=True)
    test_indexes_list_path = models.CharField(max_length=200,  null=True)
    test_indexes_list_path = models.CharField(max_length=200,  null=True)
    imagecount = models.IntegerField(  null=True)
    num_training_img = models.IntegerField( null=True)
    num_validation_img = models.IntegerField( null=True)
    epocs = models.IntegerField( null=True)
    batch_size = models.IntegerField( null=True)
    loss = models.CharField(max_length=20,  null=True)
    metrics = models.CharField(max_length=20,  null=True)
    optimizer = models.CharField(max_length=20,  null=True)
    power = models.IntegerField( null=True)
    n_blocks = models.IntegerField( null=True)
    normalization = models.CharField(max_length=20,  null=True)
    learning_rate = models.FloatField( null=True)
